apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
      - name: nginx
        image: cr.yandex/crp7mdc71bpnqapssran/nginx-static-app:817d91e6ab76dd96fc6ad22684790acf5d8e71e5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-static